#!/bin/bash
set -e

module=$(git remote get-url ssh | sed 's/.*\///' | sed 's/\.git//')
v=$(git describe)

s3d-push-down() {
  sed -i "s/$module?ref=.*\"/$module?ref=$v\"/" *.tf
  s3d-push
}

s3d-flow-down() {
  s3d-flow
}

# Push down the version changes but do not run flows. Spliting the operation in
# this way helps to avoid issues with upgrade ordering that would otherwise
# occur.
(cd ../aws-acm && s3d-push-down)
(cd ../aws-ec2 && s3d-push-down)
(cd ../aws-ecr && s3d-push-down)
(cd ../aws-eks && s3d-push-down)
(cd ../aws-sg-eg-open && s3d-push-down)
(cd ../aws-sg-ig-open && s3d-push-down)
(cd ../aws-sg-ig-ssh && s3d-push-down)
(cd ../aws-site && s3d-push-down)
(cd ../aws-site-group && s3d-push-down)
(cd ../aws-waf && s3d-push-down)

# Now run all the flows
(cd ../aws-acm && s3d-flow-down)
(cd ../aws-ec2 && s3d-flow-down)
(cd ../aws-ecr && s3d-flow-down)
(cd ../aws-eks && s3d-flow-down)
(cd ../aws-sg-eg-open && s3d-flow-down)
(cd ../aws-sg-ig-open && s3d-flow-down)
(cd ../aws-sg-ig-ssh && s3d-flow-down)
(cd ../aws-site && s3d-flow-down)
(cd ../aws-site-group && s3d-flow-down)
(cd ../aws-waf && s3d-flow-down)
